using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerBullet : MonoBehaviour
{
    public int atk;
    private void Awake()
    {
    }
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Enemy"))
        {
            collision.GetComponent<Enemy>().OnDamage(atk);//Enemy ФФЦїГЭЦЎ(ГЛАЁ ИИЕч НКХЉИГЦЎ) КвЗЏПТ ШФ OnDamage(atkАЊ ГжРК ШФ) НЧЧр
            //ЕЅЙЬСі
            Destroy(this.gameObject);
        }
    }

    private void OnBecameInvisible()
    {
        Destroy(this.gameObject);
    }
}
